import { shiprocketClient } from "@/lib/integrations/shiprocket"
import { getOrderWithOpsRelationsSupabase } from "@/src/lib/db/orders"

export async function fetchShiprocketInvoiceUrl(orderId: string) {
  const orderRecord = await getOrderWithOpsRelationsSupabase(orderId)
  if (!orderRecord) throw new Error("Order not found")

  const raw = (orderRecord as { shiprocketRawResponse?: Record<string, unknown> | null }).shiprocketRawResponse
  let srOrderId = (orderRecord as { shiprocketOrderId?: string | number | null }).shiprocketOrderId
  if (!srOrderId && raw) {
    const nested = raw.data as Record<string, unknown> | undefined
    srOrderId = (raw.order_id ?? raw.orderId ?? nested?.order_id) as string | number | null
  }
  const numericSrOrderId = Number(srOrderId)
  if (!Number.isFinite(numericSrOrderId) || numericSrOrderId <= 0) {
    throw new Error("Shiprocket invoice is not ready for this order yet.")
  }

  const res = await shiprocketClient.generateInvoice([numericSrOrderId])
  const invoiceUrl = res.invoice_url || (res as { invoice_pdf_url?: string }).invoice_pdf_url || (res as { pdf_url?: string }).pdf_url || (res as { result?: { invoice_url?: string } }).result?.invoice_url
  if (!invoiceUrl) {
    throw new Error((res as { message?: string }).message || "Invoice not yet generated by Shiprocket")
  }
  return invoiceUrl
}
