export const ROLE_KEYS = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  CUSTOMER: "customer",
} as const

export type RoleKey = (typeof ROLE_KEYS)[keyof typeof ROLE_KEYS]

export const permissionsByRole: Record<RoleKey, string[]> = {
  super_admin: ["*"],
  admin: [
    "dashboard.read",
    "products.read",
    "products.create",
    "products.update",
    "products.delete",
    "orders.read",
    "orders.update",
    "cms.read",
    "cms.update",
    "categories.read",
    "categories.create",
    "categories.update",
    "coupons.read",
    "coupons.create",
    "coupons.update",
    "users.read",
    "users.update",
    "settings.read",
    "settings.update",
    "tickets.read",
    "tickets.update",
    "reports.read",
    "notifications.read",
    "brands.read",
    "brands.create",
    "tags.read",
    "tags.create",
    "tags.edit",
    "attributes.read",
    "attributes.create",
    "inventory.read",
    "inventory.update",
    "inventory.lots.read",
    "inventory.lots.create",
    "warehouses.read",
    "warehouses.create",
    "warehouses.update",
    "bundles.read",
    "bundles.create",
    "bundles.update",
    "compliance.read",
    "compliance.update",
    "serviceability.read",
    "serviceability.update",
    "reports.enterprise.read",
    "customers.read",
    "segments.read",
    "campaigns.manage",
    "coupons.bulk.create",
    "integrations.read",
    "integrations.update",
    "reviews.read",
    "reviews.update",
    "reviews.create",
    "returns.read",
    "returns.update",
    "abandoned.read",
    "promotions.read",
    "promotions.create",
    "promotions.update",
    "finance.read",
    "finance.update",
    "users.create",
    "addresses.read",
    "addresses.write",
    "product_usage.read",
    "product_usage.create",
    "product_usage.update",
    "product_usage.delete",
    "product_usage.publish",
    "product_usage.seo",
    "product_usage.navigation",
  ],
  customer: [
    "notifications.read",
    "orders.read",
    "addresses.read",
    "addresses.write",
    "reviews.create",
    "returns.create",
    "coupons.read",
  ],
}

export const hasPermission = (role: RoleKey, permission: string) => {
  const allowed = permissionsByRole[role] ?? []
  return allowed.includes("*") || allowed.includes(permission)
}
